# Generated by Django 4.2 on 2023-11-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_newsmodels_link_alter_newsmodels_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodels',
            name='link',
            field=models.URLField(max_length=120),
        ),
        migrations.AlterField(
            model_name='newsmodels',
            name='photo',
            field=models.URLField(max_length=300),
        ),
    ]
