# Generated by Django 4.2 on 2023-11-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_newsmodels_link_alter_newsmodels_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodels',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterModelTable(
            name='newsmodels',
            table='news.db',
        ),
    ]
