# Generated by Django 4.2 on 2023-11-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_newsmodels_photo_alter_newsmodels_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodels',
            name='photo',
            field=models.CharField(max_length=400),
        ),
    ]
