# Generated by Django 4.2 on 2023-11-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_newsmodels_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodels',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
