# Generated by Django 4.2 on 2023-11-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_newsmodels_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodels',
            name='content',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newsmodels',
            name='date_time',
            field=models.SlugField(max_length=10),
        ),
        migrations.AlterField(
            model_name='newsmodels',
            name='link',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newsmodels',
            name='photo',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsmodels',
            name='title',
            field=models.SlugField(max_length=80),
        ),
    ]
