# Generated by Django 4.2 on 2023-11-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_newsmodels_content_alter_newsmodels_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodels',
            name='content',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='newsmodels',
            name='date_time',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='newsmodels',
            name='link',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='newsmodels',
            name='photo',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='newsmodels',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
